const malePlayers = [
  "Dale Condon",
  "Gino French",
  "Lonnie Carrillo",
  "Dorian Kemp",
  "Hans Yi",
  "Karl Embry",
  "Khalil Wiese",
  "Stephon Willett",
  "Ricardo Titus",
  "Jamir Ammons",
  "Shane Mann",
  "Duane Sowers",
  "Christion Owens",
  "Geoffrey Holland",
  "Tyreke Willson",
  "Alejandro Dozier",
  "Fidel Olivarez",
  "Corey Gaskins",
  "Earl Talbot",
  "Diego Barlow",
  "Rory Cochran",
  "Jaydon Knutson",
  "Shelton Tate",
  "Andres French",
  "Jaylon Kohn",
  "Stanley Cole",
  "Patrick Porras",
  "Dylon Bradshaw",
  "Nathaniel Whitten",
  "Brady Kopp",
  "Devin Lara",
  "Jonathon Coons",
  "Jaxson Heaton",
  "Pranav Terrell",
  "Kenton Wirth",
  "Eliseo Crenshaw",
  "Jerry Pratt",
  "Francesco Brewer",
  "Ariel Koenig",
  "Drew Montano",
  "Harry Severson",
  "Liam Lenz",
  "Diego Lehmann",
  "Kirk Beattie",
  "Hernan Willingham",
  "Nash Shea",
  "Jelani Swafford",
  "Trae Horn",
  "Philip Dugan",
  "Dusty Kirchner",
  "Neil Aaron",
  "Chaz Heckman",
  "Dimitri Browning",
  "Brenden Lunsford",
  "Ruben Mclemore",
  "Matteo Krueger",
  "Zayne Larkin",
  "Eduardo Bethea",
  "Dexter Paulsen",
  "Chandler Casper",
  "Everett Metcalf",
  "Jalon Mohr",
  "Gilbert Shannon",
  "Jimmie Demers",
  "Jaylon Heaton",
  "Diego Graf",
  "Logan Leger",
  "Zavier Lloyd",
  "Denver Lassiter",
  "Joe Fountain",
  "Tate Hutchings",
  "Maximiliano Romero",
  "Antonio Schmid",
  "Marcellus Starkey",
  "Niko Jeffery",
  "Peter Goss",
  "Mateo Lam",
  "August Alonzo",
  "Mohammad Kahn",
  "Jelani Kaur",
  "Kylan Derrick",
  "Jarred Bradley",
  "Leon Coles",
  "Jeremiah Dewitt",
  "Cooper Owen",
  "Cooper Addison",
  "Melvin Troyer",
  "Marvin English",
  "Adonis Maples",
  "Troy Hendricks",
  "Destin Slade",
  "Frank Kovach",
  "Federico Winslow",
  "Floyd Marshall",
  "Ashton Bernal",
  "Jude Medina",
  "Jared Ayers",
  "Turner Bruno",
  "Darrian Madrid",
  "Noel Still",
];

const femalePlayers = [
  "Isela Laster",
  "Yazmin Anthony",
  "Haley Kaufman",
  "Journey Figueroa",
  "Priscila Castro",
  "Lizbeth Greiner",
  "Kourtney Dickens",
  "Jessenia Goldberg",
  "Anjali Ashby",
  "Tatum Luu",
  "Iman McCormack",
  "Irene Preston",
  "Cherokee Killian",
  "Leeann Jarvis",
  "Lisbeth Kong",
  "Star Crenshaw",
  "Sarahi Oh",
  "Kerry Nowak",
  "Maiya Seal",
  "Hayden Poston",
  "Kylah Darnell",
  "Claire Talbert",
  "Litzy Menendez",
  "Riya Hood",
  "Tiara Navarro",
  "Ellen Ray",
  "Kyleigh Dillon",
  "Toni Waldrop",
  "Jasmin Ritchie",
  "Gianna Fuchs",
  "Kaylea Neill",
  "Amirah Baca",
  "Alea Childs",
  "Nichole Johansen",
  "Shiann Swenson",
  "Marie Patino",
  "Katarina Skaggs",
  "Maranda Beaver",
  "Elizabeth Morin",
  "Aliya Sneed",
  "Niya Calhoun",
  "Jaylene Haggard",
  "Gladys Guerrero",
  "Makena Cooley",
  "Dariana Smiley",
  "Shivani Poston",
  "Chanel Hiatt",
  "Selene Rowell",
  "Kaylie Witte",
  "Astrid Lamar",
  "Cathryn Glenn",
  "Alisa Fontenot",
  "Jessie Pickett",
  "Laney Newcomb",
  "Alessandra Kelly",
  "Leeann Boykin",
  "Saige Whitten",
  "India Johnson",
  "Maren Lyle",
  "Brynn Hiatt",
  "Cheyanne Cadena",
  "Tamya Cabrera",
  "Emilee Hussain",
  "Shania Redmond",
  "Verania Couture",
  "Mattie Winchester",
  "Gracelyn Corrales",
  "Jaela Poole",
  "Leann Boothe",
  "Jaime Hinkle",
  "Susan Wicks",
  "Adamaris Larsen",
  "Tatyana Rudolph",
  "Anabel Beckman",
  "Demi Westmoreland",
  "Kayle Shen",
  "Iyana Irvin",
  "Krysta Randolph",
  "Ainsley Kirby",
  "Tierra Lumpkin",
  "Gissell Ford",
  "Treasure Gonzales",
  "Kelsey Paquette",
  "Katheryn Nettles",
  "Daniella Christianson",
  "Rebecca Boudreaux",
  "Meghan Weiner",
  "Tiarra Frye",
  "Mira Smalley",
  "Tehya Hennessy",
  "Chasity Chamberlin",
  "Caley Tisdale",
  "Jennah Meza",
  "Margaret Carrington",
  "Diana Hardwick",
  "Jewel Randle",
  "Hillary Noe",
  "Kallie Dalton",
  "Tanya Owen",
  "Lauren Cabrera",
];

loadTableData(malePlayers);

function loadTableData(data) {
  const tableBody = document.getElementById("table-body");
  let dataHtml = ``;
  let count = 1;

  for (let person of data) {
    if (count <= 10) {
      dataHtml += `<tr><td>${count}</td><td>${person}</td><td>${0}</td><td>${0}</td><td>000 - 000</td><td>${0}</td><td>${0}</td></tr>`;
    }
    count++;
  }

  tableBody.innerHTML = dataHtml;
}



